version: '3.5'

services:
  zookeeper:
    container_name: 'zookeeper-server'
    image: bitnami/zookeeper:latest
    networks:
        - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
        - 2181:2181

  kafka:
    container_name: 'kafka-server'
    image: bitnami/kafka:latest
    networks:
        - kafka-network
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
    

networks:
  kafka-network: 
    name: 'kafka-network'
